[project]
name = "music-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mutagen>=1.47.0",
    "requests>=2.32.5",
    "yt-dlp>=2025.12.8",
    "ytmusicapi>=1.11.4",
]
